# Generated by Django 3.1.4 on 2021-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210503_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
